development:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/development.sqlite3

production:
  adapter: postgresql
  pool: 5
  encoding: unicode
  host: localhost
  username: minty
  password: wuCue8da
  database: minty_db